### ISSUE TITLE
NameError: uninitialized constant Tumblr 

### ISSUE THREAD

**Issue by ghost** [matenia/tumblr#1]
Hi,

I have been looking for tumblr plugin for my rails apps :)
But it's hit an error when I try it. 
It said NameError: uninitialized constant Tumblr.

I am using rails 3.0.7 with ruby 1.8.7

Thanks

**Comment by fajrif** [comment]
This gem works fine with me! I think you need to required it first before you use it.

In my `Gemfile` I added the gem like this :

`gem matenia-tumblr-api`

and in my ruby code :

`require 'tumblr'`

`user = Tumblr::User.new('youremailtumblr', 'yourpassword', false)`

`@posts = Tumblr::Post.all(user)`

**Comment by fhwang** [comment]
I had this issue until I changed my Gemfile line to:

```
gem "matenia-tumblr-api", "~> 0.1.6", :require => 'tumblr'
```

Without that :require directive, Bundler will try to load a file called matenia-tumblr-api.rb instead.
